# fly.toml app configuration file generated for silent-alarm on 2023-09-23T15:12:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "swarm-fitbit-alarm"
primary_region = "ams"

[env]
  PORT = "3000"

[http_service]
# internal_port=3000 will send all requests going to fly.io port 443 (HTTPS) to 3000.
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
